server:
  port: 9000
#  ssl:
#    key-store: classpath:colaba.pfx
#    key-store-password: password
#    key-store-type: PKCS12

spring:
  webflux:
    static-path-pattern: /static/**
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          include-expression: serviceId.endsWith('-UI')
          url-expression: "'lb:http://'+serviceId"

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
